## Cross-validation tests: verify NimNet algorithm outputs against
## reference values computed by NetworkX 3.6.
##
## Every expected value was generated by tests/generate_reference.py
## and verified against NetworkX. This ensures algorithmic correctness,
## not just structural properties.

import std/[unittest, tables, sets, math, sequtils, json]
import nimnet
import nimnet/algorithms/components as comp

const Eps = 1e-6
const EpsLoose = 1e-4  # for iterative algorithms (PageRank, HITS)

# ============================================================
# Helper: build the weighted graph from reference
# ============================================================
proc buildWeightedGraph(): Graph[int] =
  ## WG from generate_reference.py:
  ##   edges: (0,1,4), (0,2,2), (1,2,1), (1,3,5), (2,3,8), (2,4,10), (3,4,2)
  result = newGraph[int]()
  result.addWeightedEdge(0, 1, 4.0)
  result.addWeightedEdge(0, 2, 2.0)
  result.addWeightedEdge(1, 2, 1.0)
  result.addWeightedEdge(1, 3, 5.0)
  result.addWeightedEdge(2, 3, 8.0)
  result.addWeightedEdge(2, 4, 10.0)
  result.addWeightedEdge(3, 4, 2.0)

proc buildFlowGraph(): DiGraph[int] =
  ## FG from generate_reference.py
  result = newDiGraph[int]()
  result.addEdge(0, 1)
  var a01 = newEdgeAttr()
  a01["weight"] = newJString("10")
  result.setEdgeAttr(0, 1, a01)
  result.addEdge(0, 2)
  var a02 = newEdgeAttr()
  a02["weight"] = newJString("8")
  result.setEdgeAttr(0, 2, a02)
  result.addEdge(1, 3)
  var a13 = newEdgeAttr()
  a13["weight"] = newJString("5")
  result.setEdgeAttr(1, 3, a13)
  result.addEdge(1, 2)
  var a12 = newEdgeAttr()
  a12["weight"] = newJString("2")
  result.setEdgeAttr(1, 2, a12)
  result.addEdge(2, 4)
  var a24 = newEdgeAttr()
  a24["weight"] = newJString("10")
  result.setEdgeAttr(2, 4, a24)
  result.addEdge(3, 5)
  var a35 = newEdgeAttr()
  a35["weight"] = newJString("7")
  result.setEdgeAttr(3, 5, a35)
  result.addEdge(4, 3)
  var a43 = newEdgeAttr()
  a43["weight"] = newJString("8")
  result.setEdgeAttr(4, 3, a43)
  result.addEdge(4, 5)
  var a45 = newEdgeAttr()
  a45["weight"] = newJString("10")
  result.setEdgeAttr(4, 5, a45)

proc buildDirectedGraph(): DiGraph[int] =
  ## DG from generate_reference.py:
  ##   edges: (0,1), (1,2), (2,0), (2,3), (3,4), (4,3)
  result = newDiGraph[int]()
  result.addEdge(0, 1)
  result.addEdge(1, 2)
  result.addEdge(2, 0)
  result.addEdge(2, 3)
  result.addEdge(3, 4)
  result.addEdge(4, 3)

# ============================================================
# Karate Club Graph — comprehensive cross-validation
# ============================================================
suite "NetworkX cross-validation: Karate Club":
  let K = karateClubGraph()

  test "graph structure":
    check K.numberOfNodes() == 34
    check K.numberOfEdges() == 78

  test "shortest path 0→33 (length)":
    let sp = shortestPath(K, 0, 33)
    # Multiple valid shortest paths exist (e.g. [0,8,33] or [0,31,33])
    check sp.len == 3
    check sp[0] == 0
    check sp[^1] == 33
    check shortestPathLength(K, 0, 33) == 2

  test "diameter":
    check diameter(K) == 5

  test "radius":
    check radius(K) == 3

  test "center nodes":
    let c = center(K)
    # NetworkX: [0, 1, 2, 3, 8, 13, 19, 31]
    for n in [0, 1, 2, 3, 8, 13, 19, 31]:
      check n in c
    check c.len == 8

  test "eccentricity":
    check eccentricity(K, 0) == 3
    check eccentricity(K, 33) == 4
    check eccentricity(K, 2) == 3

  test "degree centrality top nodes":
    let dc = degreeCentrality(K)
    # NetworkX: node 33 = 0.5151515152, node 0 = 0.4848484848
    check abs(dc[33] - 0.5151515152) < Eps
    check abs(dc[0] - 0.4848484848) < Eps
    check abs(dc[32] - 0.3636363636) < Eps
    check abs(dc[2] - 0.3030303030) < Eps
    check abs(dc[1] - 0.2727272727) < Eps

  test "closeness centrality":
    let cc = closenessCentrality(K)
    check abs(cc[0] - 0.5689655172) < Eps
    check abs(cc[2] - 0.5593220339) < Eps
    check abs(cc[33] - 0.5500000000) < Eps

  test "betweenness centrality":
    let bc = betweennessCentrality(K)
    check abs(bc[0] - 0.4376352814) < Eps
    check abs(bc[2] - 0.1436568062) < Eps
    check abs(bc[33] - 0.3040749759) < Eps

  test "pagerank":
    let pr = pageRank(K)
    # Sum must be 1.0
    var total = 0.0
    for v in pr.values:
      total += v
    check abs(total - 1.0) < EpsLoose
    # NetworkX unweighted reference values (weight=None)
    check abs(pr[0] - 0.0970018176) < EpsLoose
    check abs(pr[2] - 0.0570784230) < EpsLoose
    check abs(pr[33] - 0.1009179167) < EpsLoose

  test "clustering coefficient":
    let cl = clustering(K)
    check abs(cl[0] - 0.1500000000) < Eps
    check abs(cl[2] - 0.2444444444) < Eps
    check abs(cl[33] - 0.1102941176) < Eps

  test "average clustering":
    check abs(averageClustering(K) - 0.5706384782) < Eps

  test "transitivity":
    check abs(transitivity(K) - 0.2556818182) < Eps

  test "triangle count":
    check triangles(K, 0) == 18
    check triangles(K, 33) == 15

  test "connectivity":
    check comp.isConnected(K) == true
    check numberOfConnectedComponents(K) == 1

  test "wiener index":
    check wienerIndex(K) == 1351

  test "global efficiency":
    check abs(globalEfficiency(K) - 0.4920083185) < Eps

  test "core number":
    let cn = coreNumber(K)
    check cn[0] == 4
    check cn[1] == 4
    check cn[2] == 4
    check cn[33] == 4

# ============================================================
# Petersen Graph
# ============================================================
suite "NetworkX cross-validation: Petersen Graph":
  let P = petersenGraph()

  test "graph structure":
    check P.numberOfNodes() == 10
    check P.numberOfEdges() == 15

  test "diameter":
    check diameter(P) == 2

  test "radius":
    check radius(P) == 2

  test "girth":
    check girth(P) == 5

  test "connectivity":
    check comp.isConnected(P) == true

  test "clustering":
    check abs(averageClustering(P) - 0.0) < Eps
    check abs(transitivity(P) - 0.0) < Eps

  test "wiener index":
    check wienerIndex(P) == 75

  test "pagerank symmetry":
    let pr = pageRank(P)
    # All nodes should have equal PageRank = 0.1
    for n in P.nodes:
      check abs(pr[n] - 0.1) < EpsLoose

  test "core number all 3":
    let cn = coreNumber(P)
    for n in P.nodes:
      check cn[n] == 3

# ============================================================
# Path Graph P5
# ============================================================
suite "NetworkX cross-validation: Path Graph P5":
  let P5 = pathGraph[int](5)

  test "distance measures":
    check diameter(P5) == 4
    check radius(P5) == 2
    let c = center(P5)
    check c == @[2]
    let p = periphery(P5)
    check 0 in p
    check 4 in p
    check p.len == 2

  test "betweenness centrality exact values":
    let bc = betweennessCentrality(P5)
    check abs(bc[0] - 0.0) < Eps
    check abs(bc[1] - 0.5) < Eps
    check abs(bc[2] - 0.6666666667) < Eps
    check abs(bc[3] - 0.5) < Eps
    check abs(bc[4] - 0.0) < Eps

  test "closeness centrality exact values":
    let cc = closenessCentrality(P5)
    check abs(cc[0] - 0.4) < Eps
    check abs(cc[1] - 0.5714285714) < Eps
    check abs(cc[2] - 0.6666666667) < Eps
    check abs(cc[3] - 0.5714285714) < Eps
    check abs(cc[4] - 0.4) < Eps

  test "shortest path":
    check shortestPath(P5, 0, 4) == @[0, 1, 2, 3, 4]

  test "wiener index":
    check wienerIndex(P5) == 20

# ============================================================
# Complete Graph K5
# ============================================================
suite "NetworkX cross-validation: Complete Graph K5":
  let K5 = completeGraph[int](5)

  test "distance measures":
    check diameter(K5) == 1
    check radius(K5) == 1

  test "clustering":
    check abs(averageClustering(K5) - 1.0) < Eps
    check abs(transitivity(K5) - 1.0) < Eps

  test "wiener index":
    check wienerIndex(K5) == 10

  test "global efficiency":
    check abs(globalEfficiency(K5) - 1.0) < Eps

  test "triangle count":
    for n in 0 ..< 5:
      check triangles(K5, n) == 6

  test "betweenness all zero":
    let bc = betweennessCentrality(K5)
    for n in 0 ..< 5:
      check abs(bc[n]) < Eps

# ============================================================
# Cycle Graph C6
# ============================================================
suite "NetworkX cross-validation: Cycle Graph C6":
  let C6 = cycleGraph[int](6)

  test "distance measures":
    check diameter(C6) == 3
    check radius(C6) == 3

  test "girth":
    check girth(C6) == 6

  test "clustering":
    check abs(averageClustering(C6) - 0.0) < Eps
    check abs(transitivity(C6) - 0.0) < Eps

  test "wiener index":
    check wienerIndex(C6) == 27

  test "global efficiency":
    check abs(globalEfficiency(C6) - 0.6666666667) < Eps

  test "pagerank symmetry":
    let pr = pageRank(C6)
    for n in 0 ..< 6:
      check abs(pr[n] - 1.0 / 6.0) < EpsLoose

# ============================================================
# Directed Graph — PageRank, HITS, SCC
# ============================================================
suite "NetworkX cross-validation: Directed Graph":
  let dg = buildDirectedGraph()

  test "graph structure":
    check dg.numberOfNodes() == 5
    check dg.numberOfEdges() == 6

  test "pagerank exact values":
    let pr = pageRank(dg)
    check abs(pr[0] - 0.0773338144) < EpsLoose
    check abs(pr[1] - 0.0957337422) < EpsLoose
    check abs(pr[2] - 0.1113736809) < EpsLoose
    check abs(pr[3] - 0.3705733994) < EpsLoose
    check abs(pr[4] - 0.3449853631) < EpsLoose

  test "hits hub and authority values":
    let (hubs, auths) = hits(dg)
    # NetworkX HITS with L1 normalization (sum = 1)
    check abs(hubs[2] - 0.6180339887) < EpsLoose
    check abs(hubs[4] - 0.3819660113) < EpsLoose
    check abs(auths[0] - 0.3819660113) < EpsLoose
    check abs(auths[3] - 0.6180339887) < EpsLoose
    # Verify L1 norm (sum = 1)
    var hSum, aSum = 0.0
    for v in hubs.values: hSum += v
    for v in auths.values: aSum += v
    check abs(hSum - 1.0) < EpsLoose
    check abs(aSum - 1.0) < EpsLoose

  test "strongly connected components":
    let sccs = stronglyConnectedComponents(dg)
    check sccs.len == 2
    # SCC 1: {0, 1, 2}, SCC 2: {3, 4}
    var found012 = false
    var found34 = false
    for scc in sccs:
      if scc.len == 3 and 0 in scc and 1 in scc and 2 in scc:
        found012 = true
      if scc.len == 2 and 3 in scc and 4 in scc:
        found34 = true
    check found012
    check found34

# ============================================================
# Weighted Graph — Dijkstra, MST
# ============================================================
suite "NetworkX cross-validation: Weighted Graph":
  let wg = buildWeightedGraph()

  test "dijkstra path 0→4":
    let path = dijkstraPath(wg, 0, 4)
    # NetworkX: [0, 2, 1, 3, 4]
    check path == @[0, 2, 1, 3, 4]

  test "dijkstra path length 0→4":
    let length = dijkstraPathLength(wg, 0, 4)
    # NetworkX: 10.0  (0→2: 2, 2→1: 1, 1→3: 5, 3→4: 2)
    check abs(length - 10.0) < Eps

  test "dijkstra path 0→3":
    let path = dijkstraPath(wg, 0, 3)
    check path == @[0, 2, 1, 3]

  test "dijkstra path length 0→3":
    let length = dijkstraPathLength(wg, 0, 3)
    check abs(length - 8.0) < Eps

  test "kruskal MST weight":
    let w = kruskalMSTWeight(wg)
    # NetworkX: 10.0  (edges: (0,2)=2, (1,2)=1, (1,3)=5, (3,4)=2)
    check abs(w - 10.0) < Eps

  test "kruskal MST edges":
    let mst = kruskalMST(wg)
    check mst.numberOfEdges() == 4  # n-1 = 5-1 = 4
    check mst.numberOfNodes() == 5
    # Verify expected MST edges exist
    check mst.hasEdge(0, 2)
    check mst.hasEdge(1, 2)
    check mst.hasEdge(1, 3)
    check mst.hasEdge(3, 4)

# ============================================================
# Max Flow
# ============================================================
suite "NetworkX cross-validation: Max Flow":
  test "max flow value":
    let fg = buildFlowGraph()
    let val = maximumFlowValue(fg, 0, 5)
    # NetworkX: 15.0
    check abs(val - 15.0) < Eps

# ============================================================
# All Simple Paths
# ============================================================
suite "NetworkX cross-validation: All Simple Paths":
  var g = newGraph[int]()
  g.addEdge(0, 1)
  g.addEdge(0, 2)
  g.addEdge(1, 3)
  g.addEdge(2, 3)
  g.addEdge(1, 2)

  test "all paths 0→3":
    var paths: seq[seq[int]]
    for p in allSimplePaths(g, 0, 3):
      paths.add(p)
    # NetworkX: [[0,1,2,3], [0,1,3], [0,2,1,3], [0,2,3]]
    check paths.len == 4
    check @[0, 1, 2, 3] in paths
    check @[0, 1, 3] in paths
    check @[0, 2, 1, 3] in paths
    check @[0, 2, 3] in paths

  test "paths with cutoff=2":
    var paths: seq[seq[int]]
    for p in allSimplePaths(g, 0, 3, cutoff=2):
      paths.add(p)
    # NetworkX: [[0,1,3], [0,2,3]]
    check paths.len == 2
    check @[0, 1, 3] in paths
    check @[0, 2, 3] in paths

# ============================================================
# Graph Products
# ============================================================
suite "NetworkX cross-validation: Graph Products":
  let g1 = pathGraph[int](3)  # 0-1-2
  let g2 = pathGraph[int](2)  # 0-1

  test "cartesian product P3 × P2":
    let cp = cartesianProduct(g1, g2)
    check cp.numberOfNodes() == 6
    check cp.numberOfEdges() == 7

  test "tensor product P3 × P2":
    let tp = tensorProduct(g1, g2)
    check tp.numberOfNodes() == 6
    check tp.numberOfEdges() == 4

  test "strong product P3 × P2":
    let sp = strongProduct(g1, g2)
    check sp.numberOfNodes() == 6
    check sp.numberOfEdges() == 11

  test "lexicographic product P3 × P2":
    let lp = lexicographicProduct(g1, g2)
    check lp.numberOfNodes() == 6
    check lp.numberOfEdges() == 11

# ============================================================
# Complete Bipartite Graph
# ============================================================
suite "NetworkX cross-validation: Complete Bipartite":
  let bg = completeBipartiteGraph(3, 4)

  test "structure":
    check bg.numberOfEdges() == 12
    check isBipartite(bg) == true
    check comp.isConnected(bg) == true

  test "diameter":
    check diameter(bg) == 2

# ============================================================
# Rich Club Coefficient (Karate Club)
# ============================================================
suite "NetworkX cross-validation: Rich Club":
  let K = karateClubGraph()

  test "rich club values":
    let rc = richClubCoefficient(K)
    # NetworkX (unnormalized):
    # rc[0] = 0.1390374332
    # rc[1] = 0.1458333333
    # rc[2] = 0.2380952381
    # rc[3] = 0.3250000000
    # rc[4] = 0.4888888889
    check abs(rc[0] - 0.1390374332) < Eps
    check abs(rc[1] - 0.1458333333) < Eps
    check abs(rc[2] - 0.2380952381) < Eps
    check abs(rc[3] - 0.3250000000) < Eps
    check abs(rc[4] - 0.4888888889) < Eps
